---
title: "income"
author: "ZHE ZHENG"
date: "6/10/2021"
output: html_document
---

```{r}
meanincome <- read_csv("~/Box/aim2/data/meanincome.csv", 
     col_types = cols(DP03_0062E = col_number(), 
        X4 = col_skip(), X5 = col_skip(), 
         X6 = col_skip(), X7 = col_skip(), 
         X8 = col_skip(), `zip code tabulation area` = col_character()))

meanincome <- meanincome[meanincome$DP03_0062E>10000,]
meanincome <- meanincome[complete.cases(meanincome$DP03_0062E),]
quantile(meanincome$DP03_0062E,c(1/3,2/3))

colnames(meanincome)[3] <- "zip"

meanincome$zip <-formatC(as.integer(meanincome$zip),width = 5,flag = "0")

quantile(meanincome$DP03_0062E[meanincome$zip%in%NJresp.1$zip|meanincome$zip%in%NYresp.1$zip|meanincome$zip%in%WAresp.1$zip],c(1/3,2/3))

NJresp.1 <- NJresp.1[NJresp.1$zip%in%njpop$zip,]
NYresp.1 <- NYresp.1[NYresp.1$zip%in%nypop$zip,]
WAresp.1 <- WAresp.1[WAresp.1$zip%in%WAarea$zip,]
```


```{r}
library(data.table )
NJincome <- merge(meanincome,NJresp.1,by.x="zip",by.y="zip")
NJincome <- data.table(NJincome)
NJincome <- NJincome[,list(resp = sum(resp),rsv=sum(rsv),bronchio=sum(bronchio),flu=sum(flu),pneusept=sum(pneumosept)), by = 'agecat1,amonthdate,DP03_0062E,zip']
resp.group1 <- NJincome[NJincome$DP03_0062E<44447,]
resp.group1 <- resp.group1[order(resp.group1$amonthdate),]
resp.group2 <- NJincome[NJincome$DP03_0062E>=44447&NJincome$DP03_0062E<62005 ,]
resp.group2 <- resp.group2[order(resp.group2$amonthdate),]
resp.group3 <- NJincome[NJincome$DP03_0062E>=62005,]
resp.group3 <- resp.group3[order(resp.group3$amonthdate),]

resp.group_nj <- list()
resp.group_nj <- list(resp.group1,resp.group2,resp.group3)
```


```{r}
NYincome <- merge(meanincome,NYresp.1,by.x="zip",by.y="zip")
NYincome <- data.table(NYincome)
NYincome <- NYincome[,list(resp = sum(resp),rsv=sum(rsv),bronchio=sum(bronchio),flu=sum(flu),pneusept=sum(pneumosept)), by = 'agecat1,amonthdate,DP03_0062E,zip']
resp.group1 <- NYincome[NYincome$DP03_0062E<44447,]
resp.group1 <- resp.group1[order(resp.group1$amonthdate),]
resp.group2 <- NYincome[NYincome$DP03_0062E>=44447&NYincome$DP03_0062E<62005 ,]
resp.group2 <- resp.group2[order(resp.group2$amonthdate),]
resp.group3 <- NYincome[NYincome$DP03_0062E>=62005 ,]
resp.group3 <- resp.group3[order(resp.group3$amonthdate),]

resp.group_ny <- list()
resp.group_ny <- list(resp.group1,resp.group2,resp.group3)

```

```{r}
WAincome <-   merge(meanincome,WAresp.1,by.x="zip",by.y="zip")
WAincome <- data.table(WAincome)
WAincome <- WAincome[,list(resp = sum(resp),rsv=sum(rsv),bronchio=sum(bronchio),flu=sum(flu),pneusept=sum(pneumosept)), by = 'agecat1,amonthdate,DP03_0062E,zip']
resp.group1 <- WAincome[WAincome$DP03_0062E<44447,]
resp.group1 <- resp.group1[order(resp.group1$amonthdate),]
resp.group2 <- WAincome[WAincome$DP03_0062E>=44447&WAincome$DP03_0062E<62005,]
resp.group2 <- resp.group2[order(resp.group2$amonthdate),]
resp.group3 <- WAincome[WAincome$DP03_0062E>=62005,]
resp.group3 <- resp.group3[order(resp.group3$amonthdate),]

resp.group_wa <- list()
resp.group_wa <- list(resp.group1,resp.group2,resp.group3)
```


```{r}
y_income <- array(data=NA,dim = c(108,9,3,3))
colnames(y) <- c("<1","1-<2","2-<5","5-9","10-19","20-44","45-64","65-84",">85")

for (i in 1:3) {
  
rsv.infant <- resp.group_nj[[i]][agecat1==0,]
rsv.infant <- rsv.infant[,list(resp = sum(resp)),by = 'amonthdate']
rsv.infant <- rsv.infant[order(amonthdate),]
colnames(rsv.infant)[2] <- "infant"

rsv.12to24month <- resp.group_nj[[i]][agecat1==1,]
rsv.12to24month <- rsv.12to24month[,list(resp = sum(resp)),by = 'amonthdate']
rsv.12to24month <- rsv.12to24month[order(amonthdate),]
colnames(rsv.12to24month)[2] <- "oney"

rsv.25to60month <- resp.group_nj[[i]][1<agecat1&agecat1<5,]
rsv.25to60month <- rsv.25to60month[,list(resp = sum(resp)),by = 'amonthdate']
rsv.25to60month <- rsv.25to60month[order(amonthdate),]
colnames(rsv.25to60month)[2] <- "twoy"

rsv.5to9 <- resp.group_nj[[i]][agecat1==5,]
rsv.5to9 <- rsv.5to9[,list(resp = sum(resp)),by = 'amonthdate']
rsv.5to9 <-rsv.5to9[order(amonthdate),]
colnames(rsv.5to9)[2] <- "Five"

rsv.10to19 <- resp.group_nj[[i]][5<agecat1&agecat1<8,]
rsv.10to19 <- rsv.10to19[,list(resp = sum(resp)),by = 'amonthdate']
rsv.10to19 <-rsv.10to19[order(amonthdate),]
colnames(rsv.10to19)[2] <- "Ten"

rsv.20to44 <- resp.group_nj[[i]][7<agecat1&agecat1<13,]
rsv.20to44 <- rsv.20to44[,list(resp = sum(resp)),by = 'amonthdate']
rsv.20to44 <-rsv.20to44[order(amonthdate),]
colnames(rsv.20to44)[2] <- "Twenty"

rsv.45to64 <- resp.group_nj[[i]][12<agecat1&agecat1<17,]
rsv.45to64 <- rsv.45to64[,list(resp = sum(resp)),by = 'amonthdate']
rsv.45to64 <-rsv.45to64[order(amonthdate),]
colnames(rsv.45to64)[2] <- "Fourtyfive"

rsv.65to79  <- resp.group_nj[[i]][17<=agecat1&agecat1<=20,]
rsv.65to79  <- rsv.65to79 [,list(resp = sum(resp)),by = 'amonthdate']
rsv.65to79  <- rsv.65to79 [order(amonthdate),]
colnames(rsv.65to79)[2] <- "Sixtyfive"

rsv.elderly <- resp.group_nj[[i]][21<=agecat1,]
rsv.elderly <- rsv.elderly[,list(resp = sum(resp)),by = 'amonthdate']
rsv.elderly <-rsv.elderly[order(amonthdate),]
colnames(rsv.elderly)[2] <- "Elderly"

respcount <- merge(merge(merge(merge(merge(merge(merge(merge(merge(rsv_non,
  rsv.infant,all=T),
  rsv.12to24month, all = TRUE),
  rsv.25to60month, all = TRUE),
  rsv.5to9, all = TRUE),
  rsv.10to19, all = TRUE),
  rsv.20to44,all=T),
  rsv.45to64,all=T),
  rsv.65to79,all=T),
  rsv.elderly,all=T)

respcount[is.na(respcount)]=0
respcount <- respcount[order(amonthdate),]


y_income[,1,i,1] <- respcount$infant
y_income[,2,i,1] <- respcount$oney
y_income[,3,i,1] <- respcount$twoy
y_income[,4,i,1] <- respcount$Five
y_income[,5,i,1] <- respcount$Ten
y_income[,6,i,1] <- respcount$Twenty
y_income[,7,i,1] <- respcount$Fourtyfive
y_income[,8,i,1] <- respcount$Sixtyfive
y_income[,9,i,1] <- respcount$Elderly
print(i)
}

for (i in 1:3) {
  
rsv.infant <- resp.group_ny[[i]][agecat1==0,]
rsv.infant <- rsv.infant[,list(resp = sum(resp)),by = 'amonthdate']
rsv.infant <- rsv.infant[order(amonthdate),]
colnames(rsv.infant)[2] <- "infant"

rsv.12to24month <- resp.group_ny[[i]][agecat1==1,]
rsv.12to24month <- rsv.12to24month[,list(resp = sum(resp)),by = 'amonthdate']
rsv.12to24month <- rsv.12to24month[order(amonthdate),]
colnames(rsv.12to24month)[2] <- "oney"

rsv.25to60month <- resp.group_ny[[i]][1<agecat1&agecat1<5,]
rsv.25to60month <- rsv.25to60month[,list(resp = sum(resp)),by = 'amonthdate']
rsv.25to60month <- rsv.25to60month[order(amonthdate),]
colnames(rsv.25to60month)[2] <- "twoy"

rsv.5to9 <- resp.group_ny[[i]][agecat1==5,]
rsv.5to9 <- rsv.5to9[,list(resp = sum(resp)),by = 'amonthdate']
rsv.5to9 <-rsv.5to9[order(amonthdate),]
colnames(rsv.5to9)[2] <- "Five"

rsv.10to19 <- resp.group_ny[[i]][5<agecat1&agecat1<8,]
rsv.10to19 <- rsv.10to19[,list(resp = sum(resp)),by = 'amonthdate']
rsv.10to19 <-rsv.10to19[order(amonthdate),]
colnames(rsv.10to19)[2] <- "Ten"

rsv.20to44 <- resp.group_ny[[i]][7<agecat1&agecat1<13,]
rsv.20to44 <- rsv.20to44[,list(resp = sum(resp)),by = 'amonthdate']
rsv.20to44 <-rsv.20to44[order(amonthdate),]
colnames(rsv.20to44)[2] <- "Twenty"

rsv.45to64 <- resp.group_ny[[i]][12<agecat1&agecat1<17,]
rsv.45to64 <- rsv.45to64[,list(resp = sum(resp)),by = 'amonthdate']
rsv.45to64 <-rsv.45to64[order(amonthdate),]
colnames(rsv.45to64)[2] <- "Fourtyfive"

rsv.65to79  <- resp.group_ny[[i]][17<=agecat1&agecat1<=20,]
rsv.65to79  <- rsv.65to79 [,list(resp = sum(resp)),by = 'amonthdate']
rsv.65to79  <- rsv.65to79 [order(amonthdate),]
colnames(rsv.65to79)[2] <- "Sixtyfive"

rsv.elderly <- resp.group_ny[[i]][21<=agecat1,]
rsv.elderly <- rsv.elderly[,list(resp = sum(resp)),by = 'amonthdate']
rsv.elderly <-rsv.elderly[order(amonthdate),]
colnames(rsv.elderly)[2] <- "Elderly"

respcount <- merge(merge(merge(merge(merge(merge(merge(merge(
  rsv.infant,
  rsv.12to24month, all = TRUE),
  rsv.25to60month, all = TRUE),
  rsv.5to9, all = TRUE),
  rsv.10to19, all = TRUE),
  rsv.20to44,all=T),
  rsv.45to64,all=T),
  rsv.65to79,all=T),
  rsv.elderly,all=T) 

respcount[is.na(respcount)]=0
respcount <- respcount[order(amonthdate),]


y_income[,1,i,2] <- respcount$infant
y_income[,2,i,2] <- respcount$oney
y_income[,3,i,2] <- respcount$twoy
y_income[,4,i,2] <- respcount$Five
y_income[,5,i,2] <- respcount$Ten
y_income[,6,i,2] <- respcount$Twenty
y_income[,7,i,2] <- respcount$Fourtyfive
y_income[,8,i,2] <- respcount$Sixtyfive
y_income[,9,i,2] <- respcount$Elderly
print(i)
}

for (i in 1:3) {
  
rsv.infant <- resp.group_wa[[i]][agecat1==0,]
rsv.infant <- rsv.infant[,list(resp = sum(resp)),by = 'amonthdate']
rsv.infant <- rsv.infant[order(amonthdate),]
colnames(rsv.infant)[2] <- "infant"

rsv.12to24month <- resp.group_wa[[i]][agecat1==1,]
rsv.12to24month <- rsv.12to24month[,list(resp = sum(resp)),by = 'amonthdate']
rsv.12to24month <- rsv.12to24month[order(amonthdate),]
colnames(rsv.12to24month)[2] <- "oney"

rsv.25to60month <- resp.group_wa[[i]][1<agecat1&agecat1<5,]
rsv.25to60month <- rsv.25to60month[,list(resp = sum(resp)),by = 'amonthdate']
rsv.25to60month <- rsv.25to60month[order(amonthdate),]
colnames(rsv.25to60month)[2] <- "twoy"

rsv.5to9 <- resp.group_wa[[i]][agecat1==5,]
rsv.5to9 <- rsv.5to9[,list(resp = sum(resp)),by = 'amonthdate']
rsv.5to9 <-rsv.5to9[order(amonthdate),]
colnames(rsv.5to9)[2] <- "Five"

rsv.10to19 <- resp.group_wa[[i]][5<agecat1&agecat1<8,]
rsv.10to19 <- rsv.10to19[,list(resp = sum(resp)),by = 'amonthdate']
rsv.10to19 <-rsv.10to19[order(amonthdate),]
colnames(rsv.10to19)[2] <- "Ten"

rsv.20to44 <- resp.group_wa[[i]][7<agecat1&agecat1<13,]
rsv.20to44 <- rsv.20to44[,list(resp = sum(resp)),by = 'amonthdate']
rsv.20to44 <-rsv.20to44[order(amonthdate),]
colnames(rsv.20to44)[2] <- "Twenty"

rsv.45to64 <- resp.group_wa[[i]][12<agecat1&agecat1<17,]
rsv.45to64 <- rsv.45to64[,list(resp = sum(resp)),by = 'amonthdate']
rsv.45to64 <-rsv.45to64[order(amonthdate),]
colnames(rsv.45to64)[2] <- "Fourtyfive"

rsv.65to79  <- resp.group_wa[[i]][17<=agecat1&agecat1<=20,]
rsv.65to79  <- rsv.65to79 [,list(resp = sum(resp)),by = 'amonthdate']
rsv.65to79  <- rsv.65to79 [order(amonthdate),]
colnames(rsv.65to79)[2] <- "Sixtyfive"

rsv.elderly <- resp.group_wa[[i]][21<=agecat1,]
rsv.elderly <- rsv.elderly[,list(resp = sum(resp)),by = 'amonthdate']
rsv.elderly <-rsv.elderly[order(amonthdate),]
colnames(rsv.elderly)[2] <- "Elderly"

respcount <- merge(merge(merge(merge(merge(merge(merge(merge(
  rsv.infant,
  rsv.12to24month, all = TRUE),
  rsv.25to60month, all = TRUE),
  rsv.5to9, all = TRUE),
  rsv.10to19, all = TRUE),
  rsv.20to44,all=T),
  rsv.45to64,all=T),
  rsv.65to79,all=T),
  rsv.elderly,all=T) 

respcount[is.na(respcount)]=0
respcount <- respcount[order(amonthdate),]


y_income[,1,i,3] <- respcount$infant
y_income[,2,i,3] <- respcount$oney
y_income[,3,i,3] <- respcount$twoy
y_income[,4,i,3] <- respcount$Five
y_income[,5,i,3] <- respcount$Ten
y_income[,6,i,3] <- respcount$Twenty
y_income[,7,i,3] <- respcount$Fourtyfive
y_income[,8,i,3] <- respcount$Sixtyfive
y_income[,9,i,3] <- respcount$Elderly
print(i)
}

```

```{r}
rsv_low_nj <- resp.group_nj[[1]][agecat1<=1,]
rsv_low_nj <-  rsv_low_nj[,list(rsv=sum(rsv)), by = 'amonthdate']
rsv_low_nj <- rsv_low_nj[order(amonthdate),]

rsv_mid_nj <- resp.group_nj[[2]][agecat1<=1,]
rsv_mid_nj <-  rsv_mid_nj[,list(rsv=sum(rsv)), by = 'amonthdate']
rsv_mid_nj <- rsv_mid_nj[order(amonthdate),]

rsv_high_nj <- resp.group_nj[[3]][agecat1<=1,]
rsv_high_nj <-  rsv_high_nj[,list(rsv=sum(rsv)), by = 'amonthdate']
rsv_high_nj <- rsv_high_nj[order(amonthdate),]

rsv_low_ny <- resp.group_ny[[1]][agecat1<=1,]
rsv_low_ny <-  rsv_low_ny[,list(rsv=sum(rsv)), by = 'amonthdate']
rsv_low_ny <- rsv_low_ny[order(amonthdate),]

rsv_mid_ny <- resp.group_ny[[2]][agecat1<=1,]
rsv_mid_ny <-  rsv_mid_ny[,list(rsv=sum(rsv)), by = 'amonthdate']
rsv_mid_ny <- rsv_mid_ny[order(amonthdate),]

rsv_high_ny <- resp.group_ny[[3]][agecat1<=1,]
rsv_high_ny <-  rsv_high_ny[,list(rsv=sum(rsv)), by = 'amonthdate']
rsv_high_ny <- rsv_high_ny[order(amonthdate),]


rsv_low_wa <- resp.group_wa[[1]][agecat1<=1,]
rsv_low_wa <-  rsv_low_wa[,list(rsv=sum(rsv)), by = 'amonthdate']
rsv_low_wa <- rsv_low_wa[order(amonthdate),]

rsv_mid_wa <- resp.group_wa[[2]][agecat1<=1,]
rsv_mid_wa <-  rsv_mid_wa[,list(rsv=sum(rsv)), by = 'amonthdate']
rsv_mid_wa <- rsv_mid_wa[order(amonthdate),]

rsv_high_wa <- resp.group_wa[[3]][agecat1<=1,]
rsv_high_wa <-  rsv_high_wa[,list(rsv=sum(rsv)), by = 'amonthdate']
rsv_high_wa <- rsv_high_wa[order(amonthdate),]

rsv_income <- array(data =c(c(rep(rsv_low_nj$rsv,9),rep(rsv_mid_nj$rsv,9),rep(rsv_high_nj$rsv,9)),c(rep(rsv_low_ny$rsv,9),rep(rsv_mid_ny$rsv,9),rep(rsv_high_ny$rsv,9)),c(rep(rsv_low_wa$rsv,9),rep(rsv_mid_wa$rsv,9),rep(rsv_high_wa$rsv,9))),dim = c(108,9,3,3))
```

```{r}
flu_low_nj <- resp.group_nj[[1]][,list(flu=sum(flu)), by = 'amonthdate']
flu_low_nj <- flu_low_nj[order(amonthdate),]

flu_mid_nj <- resp.group_nj[[2]][,list(flu=sum(flu)), by = 'amonthdate']
flu_mid_nj <- flu_mid_nj[order(amonthdate),]

flu_high_nj <- resp.group_nj[[3]][,list(flu=sum(flu)), by = 'amonthdate']
flu_high_nj <- flu_high_nj[order(amonthdate),]

flu_low_ny <- resp.group_ny[[1]][,list(flu=sum(flu)), by = 'amonthdate']
flu_low_ny <- flu_low_ny[order(amonthdate),]

flu_mid_ny <- resp.group_ny[[2]][,list(flu=sum(flu)), by = 'amonthdate']
flu_mid_ny <- flu_mid_ny[order(amonthdate),]

flu_high_ny <- resp.group_ny[[3]][,list(flu=sum(flu)), by = 'amonthdate']
flu_high_ny <- flu_high_ny[order(amonthdate),]


flu_low_wa <- resp.group_wa[[1]][,list(flu=sum(flu)), by = 'amonthdate']
flu_low_wa <- flu_low_wa[order(amonthdate),]

flu_mid_wa <- resp.group_wa[[2]][,list(flu=sum(flu)), by = 'amonthdate']
flu_mid_wa <- flu_mid_wa[order(amonthdate),]

flu_high_wa <- resp.group_wa[[3]][,list(flu=sum(flu)), by = 'amonthdate']
flu_high_wa <- flu_high_wa[order(amonthdate),]

flu_income <- array(data =c(c(rep(flu_low_nj$flu,9),rep(flu_mid_nj$flu,9),rep(flu_high_nj$flu,9)),c(rep(flu_low_ny$flu,9),rep(flu_mid_ny$flu,9),rep(flu_high_ny$flu,9)),c(rep(flu_low_wa$flu,9),rep(flu_mid_wa$flu,9),rep(flu_high_wa$flu,9))),dim = c(108,9,3,3))

```

```{r}
y_income_whole <- rowSums(y_income,dims = 3)
rsv_income_whole <- rowSums(rsv_income,dims = 3)
flu_income_whole <- rowSums(flu_income,dims = 3)
```

```{r}
post1 <- as.data.frame(as.matrix(rsv_resp[[1]][-c(1:1750),]))
  post2 <- as.data.frame(as.matrix(rsv_resp[[2]][-c(1:1750),]))
  post3 <- as.data.frame(as.matrix(rsv_resp[[3]][-c(1:1750),]))
  post <- bind_rows(post1,post2,post3)
  lambda <- post[, grep("lambda", colnames(post), fixed=T)]
  rd2.resp <- post[, grep("rd2[", colnames(post), fixed=T)]
  
  rsv_count <- array(data = NA,dim = c(3750,108,9,3))
for (i in 1:108) {
  for (j in 1:9) {
    for (k in 1:3) {
      rsv_count[,i,j,k] <- rsv_income_whole[i,j,k]*rd2.resp[,j+9*(k-1)]
    }}}

  rsv_count_age <- array(data = NA,dim = c(3750,9,3))
  for (i in 1:3750) {    
    for (j in 1:9) {
      for (k in 1:3) {
       rsv_count_age[i,j,k] <- sum(rsv_count[i,,j,k])}}}
  
  rsv_percent <- array(data = NA,dim = c(3750,9,3))
for (j in 1:9) {
  for (k in 1:3) {
    rsv_percent[,j,k] <- as.numeric(rowSums(rsv_count[,,j,k])/rowSums(lambda[,((j-1)*108+(k-1)*108*9+1):((j-1)*108+(k-1)*108*9+108)]))
  }}

  round(apply(rsv_percent,c(2), mean)*100,1)
  round(apply(rsv_percent, c(2,3), quantile , probs = 0.025)*100,1)
  round(apply(rsv_percent, c(2,3), quantile , probs = 0.975)*100,1)
```

```{r}
age_pop_1 <- age_pop[age_pop$ZIP%in%resp.group_nj[[1]]$zip|age_pop$ZIP%in%resp.group_ny[[1]]$zip|age_pop$ZIP%in%resp.group_wa[[1]]$zip,]
age_pop_2 <- age_pop[age_pop$ZIP%in%resp.group_nj[[2]]$zip|age_pop$ZIP%in%resp.group_ny[[2]]$zip|age_pop$ZIP%in%resp.group_wa[[2]]$zip,]
age_pop_3 <- age_pop[age_pop$ZIP%in%resp.group_nj[[3]]$zip|age_pop$ZIP%in%resp.group_ny[[3]]$zip|age_pop$ZIP%in%resp.group_wa[[3]]$zip,]

age_number <- matrix(data=NA,nrow=9,ncol = 3)
colnames(age_number) <- c("urban","sub","rural")
rownames(age_number) <- c("<1","1","2-4","5-9","10-19","20-44","45-64","65-84","85+")
age_number[1,1] <- sum(age_pop_1$Estimate..SEX.AND.AGE..Under.5.years)/5
age_number[2,1] <- sum(age_pop_1$Estimate..SEX.AND.AGE..Under.5.years)/5
age_number[3,1] <- sum(age_pop_1$Estimate..SEX.AND.AGE..Under.5.years)/5*3
age_number[4,1] <- sum(age_pop_1$Estimate..SEX.AND.AGE..5.to.9.years)
age_number[5,1] <- sum(age_pop_1$Estimate..SEX.AND.AGE..10.to.14.years,age_pop_1$Estimate..SEX.AND.AGE..15.to.19.years)
age_number[6,1] <- sum(age_pop_1$Estimate..SEX.AND.AGE..20.to.24.years,age_pop_1$Estimate..SEX.AND.AGE..25.to.34.years,age_pop_1$Estimate..SEX.AND.AGE..35.to.44.years)
age_number[7,1] <- sum(age_pop_1$Estimate..SEX.AND.AGE..45.to.54.years,age_pop_1$Estimate..SEX.AND.AGE..55.to.59.years,age_pop_1$Estimate..SEX.AND.AGE..60.to.64.years)
age_number[8,1] <- sum(age_pop_1$Estimate..SEX.AND.AGE..65.to.74.years,
                       age_pop_1$Estimate..SEX.AND.AGE..75.to.84.years)
age_number[9,1] <- sum(age_pop_1$Estimate..SEX.AND.AGE..85.years.and.over)


age_number[1,2] <- sum(age_pop_2$Estimate..SEX.AND.AGE..Under.5.years)/5
age_number[2,2] <- sum(age_pop_2$Estimate..SEX.AND.AGE..Under.5.years)/5
age_number[3,2] <- sum(age_pop_2$Estimate..SEX.AND.AGE..Under.5.years)/5*3
age_number[4,2] <- sum(age_pop_2$Estimate..SEX.AND.AGE..5.to.9.years)
age_number[5,2] <- sum(age_pop_2$Estimate..SEX.AND.AGE..10.to.14.years,age_pop_2$Estimate..SEX.AND.AGE..15.to.19.years)
age_number[6,2] <- sum(age_pop_2$Estimate..SEX.AND.AGE..20.to.24.years,age_pop_2$Estimate..SEX.AND.AGE..25.to.34.years,age_pop_2$Estimate..SEX.AND.AGE..35.to.44.years)
age_number[7,2] <- sum(age_pop_2$Estimate..SEX.AND.AGE..45.to.54.years,age_pop_2$Estimate..SEX.AND.AGE..55.to.59.years,age_pop_2$Estimate..SEX.AND.AGE..60.to.64.years)
age_number[8,2] <- sum(age_pop_2$Estimate..SEX.AND.AGE..65.to.74.years,
                       age_pop_2$Estimate..SEX.AND.AGE..75.to.84.years)
age_number[9,2] <- sum(age_pop_2$Estimate..SEX.AND.AGE..85.years.and.over)



age_number[1,3] <- sum(age_pop_3$Estimate..SEX.AND.AGE..Under.5.years)/5
age_number[2,3] <- sum(age_pop_3$Estimate..SEX.AND.AGE..Under.5.years)/5
age_number[3,3] <- sum(age_pop_3$Estimate..SEX.AND.AGE..Under.5.years)/5*3
age_number[4,3] <- sum(age_pop_3$Estimate..SEX.AND.AGE..5.to.9.years)
age_number[5,3] <- sum(age_pop_3$Estimate..SEX.AND.AGE..10.to.14.years,age_pop_3$Estimate..SEX.AND.AGE..15.to.19.years)
age_number[6,3] <- sum(age_pop_3$Estimate..SEX.AND.AGE..20.to.24.years,age_pop_3$Estimate..SEX.AND.AGE..25.to.34.years,age_pop_3$Estimate..SEX.AND.AGE..35.to.44.years)
age_number[7,3] <- sum(age_pop_3$Estimate..SEX.AND.AGE..45.to.54.years,age_pop_3$Estimate..SEX.AND.AGE..55.to.59.years,age_pop_3$Estimate..SEX.AND.AGE..60.to.64.years)
age_number[8,3] <- sum(age_pop_3$Estimate..SEX.AND.AGE..65.to.74.years,
                       age_pop_3$Estimate..SEX.AND.AGE..75.to.84.years)
age_number[9,3] <- sum(age_pop_3$Estimate..SEX.AND.AGE..85.years.and.over)
```


```{r}
incidence <- array(data = NA,dim = c(3750,9,3))
  for (j in 1:9) {
      for (k in 1:3) {
        for (p in 1:3750) {
   incidence[p,j,k] <- (rsv_count_age[p,j,k]/age_number[j,k])/9*100000}}}

dimnames(incidence)[2] <- list(age_group=c("<1","1","2-4","5-9","10-19","20-44","45-64","65-84","85+"))

  round(apply(incidence,2, mean))
  round(apply(incidence, 2, quantile , probs = 0.025))
  round(apply(incidence,2, quantile , probs = 0.975))
  
dimnames(incidence)[3] <- list(income_group=c("Low","Medium","High"))

df0 <- as.data.frame.table(incidence)
df0 <- df0[,-1]
names(df0) <- c("age_group","income_group","RSVHosp")

df2 <- df0 %>%
  group_by(age_group,income_group) %>%
  summarise(RSVHosp_incidence = median(RSVHosp, na.rm = TRUE),
            quan_0.025 = quantile(RSVHosp, 0.025,na.rm = TRUE),
            quan_0.975 = quantile(RSVHosp, 0.975,na.rm = TRUE),
            sd=sd(RSVHosp, na.rm = TRUE))
df3 <- df2
df3$RSVHosp_incidence <- signif(df3$RSVHosp_incidence,2)
df3$RSVHosp_incidence[18] <- 10

tiff(file = "/Users/zhezheng/OneDrive/MIDAS/F1_wholeincome_Jan7.tiff",width=5500,height=2000,res=600)  
#pdf(file = "/Users/zhezheng/OneDrive/MIDAS/F1_wholeincome_Dec7.pdf",width=2200,height=1000) 
ggplot(df3, aes(x=age_group,y=RSVHosp_incidence,label=RSVHosp_incidence,color = income_group,group=income_group)) +
  geom_point(aes(x=age_group,y=RSVHosp_incidence),position=position_dodge(0.6), size = 1)+
 geom_text(position = position_dodge(width =0.7), vjust = -df2$sd/50-1, size = 3,
              fontface = "bold", show.legend = FALSE) +
  scale_y_continuous(breaks=seq(0, 3000, 250), limits=c(0, 3100))+
  geom_errorbar(
    aes(ymin = quan_0.025, ymax = quan_0.975,color = income_group),
    position = position_dodge(0.6),width=.1
    )+
  scale_color_manual(values = c("#00AFBB", "#E7B800","#FC4E07"))+
  labs(y="Estimated RSV hospitalizations\nper 100,000 people", x="Age group",color="Income level",size = 8)+
  theme_classic()+
  theme(axis.text.x = element_text(size = 8), axis.title.x = element_text(size = 10),
        axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 10),
        legend.title = element_text(size=8),
        legend.text = element_text(size = 8))
dev.off()

```
```{r}
rsv_report <- matrix(data=NA,nrow=9,ncol=3)
rownames(rsv_report) <- c("<1","1-<2","2-<5","5-9","10-19","20-44","45-64","65-84",">85")

for (i in 1:3) {
  
rsv_report[1,i] <- sum(resp.group_nj[[i]][agecat1==0,][,6],resp.group_ny[[i]][agecat1==0,][,6],resp.group_wa[[i]][agecat1==0,][,6])

rsv_report[2,i] <- sum(resp.group_nj[[i]][agecat1==1,][,6],resp.group_ny[[i]][agecat1==1,][,6],resp.group_wa[[i]][agecat1==1,][,6])

rsv_report[3,i]<- sum(resp.group_nj[[i]][1<agecat1&agecat1<5,][,6],resp.group_ny[[i]][1<agecat1&agecat1<5,][,6],resp.group_wa[[i]][1<agecat1&agecat1<5,][,6])

rsv_report[4,i] <- sum(resp.group_nj[[i]][agecat1==5,][,6],resp.group_ny[[i]][agecat1==5,][,6],resp.group_wa[[i]][agecat1==5,][,6])

rsv_report[5,i] <- sum(resp.group_nj[[i]][5<agecat1&agecat1<8,][,6],resp.group_ny[[i]][5<agecat1&agecat1<8,][,6],resp.group_wa[[i]][5<agecat1&agecat1<8,][,6])

rsv_report[6,i]<- sum(resp.group_nj[[i]][7<agecat1&agecat1<13,][,6],resp.group_ny[[i]][7<agecat1&agecat1<13,][,6],resp.group_wa[[i]][7<agecat1&agecat1<13,][,6])

rsv_report[7,i] <- sum(resp.group_nj[[i]][12<agecat1&agecat1<17,][,6],resp.group_ny[[i]][12<agecat1&agecat1<17,][,6],resp.group_wa[[i]][12<agecat1&agecat1<17,][,6])

rsv_report[8,i] <- sum(resp.group_nj[[i]][17<=agecat1&agecat1<=20,][,6],resp.group_ny[[i]][17<=agecat1&agecat1<=20,][,6],resp.group_wa[[i]][17<=agecat1&agecat1<=20,][,6])

rsv_report[9,i] <- sum(resp.group_nj[[i]][21<=agecat1,][,6],resp.group_ny[[i]][21<=agecat1,][,6],resp.group_wa[[i]][21<=agecat1,][,6])

print(i)
}

```


```{r}
rsv_age <- colMeans(rsv_count_age)
rsv_ratio <- as.data.frame(rsv_report/rsv_age)
colnames(rsv_ratio) <- c("low","medium","high")
rsv_ratio$Age <- c("<1","1","2-4","5-9","10-19","20-44","45-64","65-84","85+")
library(tidyr)
long_rsv_ratio <- rsv_ratio %>% gather("Income level", "Report ratio", low:high)
long_rsv_ratio$Age <- factor(long_rsv_ratio$Age,level=c("85+", "65-84", "45-64","20-44","10-19" , "5-9" ,"2-4", "1","<1"  ))
long_rsv_ratio$`Income level` <- factor(long_rsv_ratio$`Income level`,levels = c("low","medium","high"))

tiff(file = "/Users/zhezheng/OneDrive/MIDAS/F4whole.png",width=1100,height=900,res=380)
ggplot(data=long_rsv_ratio,aes(x=`Income level`, y=Age, size=`Report ratio`, color=`Income level`)) +
  scale_color_manual(values = c("#00AFBB", "#E7B800", "#FC4E07")) +
    geom_point(alpha=0.5) +
  geom_text(aes(label=round(`Report ratio`, digits = 2)), size=2, nudge_x=+0.45, nudge_y=0.00)+
    scale_size(range = c(0.05, 8), name="Report ratio")+
  theme(axis.text.x = element_text(size = 4), axis.title.x = element_text(size = 4),
        axis.text.y = element_text(size = 4), axis.title.y = element_text(size = 4),
        legend.title = element_text(size=4),
        legend.text = element_text(size = 4),
    panel.background = element_blank())
dev.off()
```

```{r}
long_rsv_ratio_new <- long_rsv_ratio
long_rsv_ratio_new[,3:5] <- round(long_rsv_ratio[,3:5]*100)

tiff(file = "/Users/zhezheng/OneDrive/MIDAS/donut_Jan7.tiff",width=1600,height=1600,res=380)
ggplot(data=long_rsv_ratio_new,aes(x=`Income group`, y=Age)) +
    geom_point(aes(size=lower, fill=`Income group`,color=`Income group`),alpha=0.1) +
    geom_point(aes(size=`Report ratio`, fill=`Income group`,color=`Income group`),alpha=1) +
    geom_point(aes(size=upper, fill=`Income group`,color="white"),alpha=1) +
    scale_fill_manual(values = c("#00AFBB","#E7B800", "#FC4E07"),name="Income Group",guide=T) +#
    scale_color_manual(values = c( "#FC4E07","#00AFBB", "#E7B800","white"),guide=F) +
    geom_text(aes(label=paste0(`Report ratio`,"%")), size=3, nudge_x=+0.45, nudge_y=0.00)+
    guides(size = guide_legend(override.aes = list(shape=21),order=1),
           fill = guide_legend(override.aes = list(shape=21,size=3),order=2))+
    scale_size(range = c(0.05, 14), breaks = c(10,30,50), name="Recorded Ratio",labels = paste0(c(10,30,50),"%"))+
    theme(axis.text.x = element_text(size = 8), axis.title.x = element_text(size = 10),
          axis.text.y = element_text(size = 8), axis.title.y = element_text(size = 10),
          legend.title = element_text(size=8),
          legend.text = element_text(size = 8),
          panel.background = element_blank())
dev.off()
```

## Figure 1

stacked plot

```{r}
library(dplyr)
library(tidyr)
rsv_count_estimate <- array(data = NA,dim = c(3750,108))
  for (i in 1:108) {
    for (j in 1:3750) {
        rsv_count_estimate[j,i] <- sum(rsv_count[j,i,1,])
    }}
rsv_count_estimate <- colMeans(rsv_count_estimate)
rsv_count_estimate_plot <- data.frame(state=rep("Whole",108),type=rep("Estimates",108),date=rsv_urban$amonthdate,mean=rsv_count_estimate/(sum(age_number[1,]))*100000)

infant.report <- bind_rows(NJresp.1[AGE<1,list(rsv=sum(rsv)),by="amonthdate"],NYresp.1[AGE<1,list(rsv=sum(rsv)),by="amonthdate"],WAresp.1[AGE<1,list(rsv=sum(rsv)),by="amonthdate"])
infant.report <-aggregate(infant.report$rsv, by=list(amonthdate=infant.report$amonthdate), FUN=sum)
infant.report <- infant.report[order(infant.report$amonthdate),]
rsv_count_real_plot <- data.frame(state=rep("Whole",108),type=rep("Report",108),date=infant.report$amonthdate,mean=infant.report$x/(sum(age_number[1,]))*100000)

infant.total <- bind_rows(NJresp.1[AGE<1,list(resp=sum(resp)),by="amonthdate"],NYresp.1[AGE<1,list(resp=sum(resp)),by="amonthdate"],WAresp.1[AGE<1,list(resp=sum(resp)),by="amonthdate"])
infant.total <-aggregate(infant.total$resp, by=list(amonthdate=infant.total$amonthdate), FUN=sum)
infant.total <- infant.total[order(infant.total$amonthdate),]
rsv_count_total_plot <- data.frame(state=rep("Whole",108),type=rep("Total",108),date=infant.total$amonthdate,mean=infant.total$x/(sum(age_number[1,]))*100000)

rsv_wide <- bind_rows(rsv_count_total_plot,rsv_count_estimate_plot,rsv_count_real_plot)
rsv_wide <- spread(rsv_wide, type, mean)

tiff(file = "/Users/zhezheng/OneDrive/MIDAS/F4_wholeincome_Jan7.tiff",width=14,height=8,units ="in",res=380)
ggplot(data=rsv_wide, aes(x=date)) +
 geom_area(aes(y=Total,fill="Total")) +
  geom_area(aes(y=Estimates,fill="Estimated RSV")) +
    geom_area(aes(y=Report,fill="Recorded RSV"))+
labs(y=" Hospitalizations per 100,000 children under One", x="Date")+
  theme(axis.text.x = element_text(size = 14), axis.title.x = element_text(size = 16),
        axis.text.y = element_text(size = 14), axis.title.y = element_text(size = 16),
        legend.title = element_text(size=16),
        legend.text = element_text(size = 14),
    panel.background = element_blank())+ 
    scale_fill_manual(name="Respiratory\nHospitalizations",values=c("Total"="darkturquoise","Estimated RSV"="gold","Recorded RSV"="red"),breaks=c("Total",
                           "Estimated RSV",
                           "Recorded RSV"))
dev.off()

rsv_count_estimate <- array(data = NA,dim = c(3750,108))
  for (i in 1:108) {
    for (j in 1:3750) {
        rsv_count_estimate[j,i] <- sum(rsv_count[j,i,c(8:9),])
    }}

rsv_count_estimate <- colMeans(rsv_count_estimate)
rsv_count_estimate_plot_old <- data.frame(state=rep("Whole",108),type=rep("Estimates",108),date=rsv_urban$amonthdate,mean=rsv_count_estimate/( 4565877)*100000)

report_old <- bind_rows(NJresp.1[65<=AGE,list(rsv=sum(rsv)),by="amonthdate"],NYresp.1[65<=AGE,list(rsv=sum(rsv)),by="amonthdate"],WAresp.1[65<=AGE,list(rsv=sum(rsv)),by="amonthdate"])
report_old  <-aggregate(report_old $rsv, by=list(amonthdate=report_old$amonthdate), FUN=sum)
report_old  <- report_old [order(report_old $amonthdate),]
rsv_count_real_plot_old <- data.frame(state=rep("Whole",108),type=rep("Report",108),date=report_old $amonthdate,mean=report_old $x/( 4565877)*100000)

total_old <- bind_rows(NJresp.1[65<=AGE,list(resp=sum(resp)),by="amonthdate"],NYresp.1[65<=AGE,list(resp=sum(resp)),by="amonthdate"],WAresp.1[65<=AGE,list(resp=sum(resp)),by="amonthdate"])
total_old  <-aggregate(total_old$resp, by=list(amonthdate=total_old$amonthdate), FUN=sum)
total_old  <- total_old [order(total_old$amonthdate),]
rsv_count_total_plot_old <- data.frame(state=rep("Whole",108),type=rep("Total",108),date=total_old$amonthdate,mean=total_old$x/( 4565877)*100000)

rsv_old <- bind_rows(rsv_count_total_plot_old,rsv_count_estimate_plot_old,rsv_count_real_plot_old)
rsv_old <- spread(rsv_old, type, mean)

##RSV respiratory hospitalizations in the elderly (65+) in New York
tiff(file = "/Users/zhezheng/OneDrive/MIDAS/F3_wholeincome_Jan7.tiff",width=14,height=8,units ="in",res=380)
ggplot(data=rsv_old, aes(x=date)) +
 geom_area(aes(y=Total,fill="Total")) +
  geom_area(aes(y=Estimates,fill="Estimated RSV")) +
    geom_area(aes(y=Report,fill="Recorded RSV"))+
  labs(y="Hospitalizations per 100,000 people", x="Date")+
  theme(axis.text.x = element_text(size = 12), axis.title.x = element_text(size = 16),
        axis.text.y = element_text(size = 12), axis.title.y = element_text(size = 16),
        legend.title = element_text(size=16),
        legend.text = element_text(size = 16),
    panel.background = element_blank(),
     plot.title = element_text( face = "bold",hjust = 0.5))+ 
    scale_fill_manual(name="Respiratory\nHospitalizations",values=c("Total"="darkturquoise","Estimated RSV"="gold","Recorded RSV"="red"),breaks=c("Total",
                           "Estimated RSV",
                           "Recorded RSV"))+
  facet_zoom2(ylim = c(0,75))
dev.off()
```

```{r}
round(apply(rsv_percent_nj,c(2,3), mean)*100,1)
round(apply(rsv_percent_nj, c(2,3), quantile , probs = 0.025)*100,1)
round(apply(rsv_percent_nj, c(2,3), quantile , probs = 0.975)*100,1)
```

```{r}
pneusept_report <- matrix(data=NA,nrow=9,ncol=3)
rownames(pneusept_report) <- c("<1","1-<2","2-<5","5-9","10-19","20-44","45-64","65-84",">85")

for (i in 1:3) {
  
pneusept_report[1,i] <- sum(resp.group_nj[[i]][agecat1==0,][,"pneusept"],resp.group_ny[[i]][agecat1==0,][,"pneusept"],resp.group_wa[[i]][agecat1==0,][,"pneusept"])

pneusept_report[2,i] <- sum(resp.group_nj[[i]][agecat1==1,][,"pneusept"],resp.group_ny[[i]][agecat1==1,][,"pneusept"],resp.group_wa[[i]][agecat1==1,][,"pneusept"])

pneusept_report[3,i]<- sum(resp.group_nj[[i]][1<agecat1&agecat1<5,][,"pneusept"],resp.group_ny[[i]][1<agecat1&agecat1<5,][,"pneusept"],resp.group_wa[[i]][1<agecat1&agecat1<5,][,"pneusept"])

pneusept_report[4,i] <- sum(resp.group_nj[[i]][agecat1==5,][,"pneusept"],resp.group_ny[[i]][agecat1==5,][,"pneusept"],resp.group_wa[[i]][agecat1==5,][,"pneusept"])

pneusept_report[5,i] <- sum(resp.group_nj[[i]][5<agecat1&agecat1<8,][,"pneusept"],resp.group_ny[[i]][5<agecat1&agecat1<8,][,"pneusept"],resp.group_wa[[i]][5<agecat1&agecat1<8,][,"pneusept"])

pneusept_report[6,i]<- sum(resp.group_nj[[i]][7<agecat1&agecat1<13,][,"pneusept"],resp.group_ny[[i]][7<agecat1&agecat1<13,][,"pneusept"],resp.group_wa[[i]][7<agecat1&agecat1<13,][,"pneusept"])

pneusept_report[7,i] <- sum(resp.group_nj[[i]][12<agecat1&agecat1<17,][,"pneusept"],resp.group_ny[[i]][12<agecat1&agecat1<17,][,"pneusept"],resp.group_wa[[i]][12<agecat1&agecat1<17,][,"pneusept"])

pneusept_report[8,i] <- sum(resp.group_nj[[i]][17<=agecat1&agecat1<=20,][,"pneusept"],resp.group_ny[[i]][17<=agecat1&agecat1<=20,][,"pneusept"],resp.group_wa[[i]][17<=agecat1&agecat1<=20,][,"pneusept"])

pneusept_report[9,i] <- sum(resp.group_nj[[i]][21<=agecat1,][,"pneusept"],resp.group_ny[[i]][21<=agecat1,][,"pneusept"],resp.group_wa[[i]][21<=agecat1,][,"pneusept"])

print(i)
}

```

```{r}
round(pneusept_report/age_number*100000,0)
  
```

